In [1]:
pip install -r requirements.txt

Requirement already satisfied: pandas in c:\python\lib\site-packages (from -r requirements.txt (line 1)) (3.0.2)
Collecting streamlit (from -r requirements.txt (line 2))
  Using cached streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: langchain in c:\python\lib\site-packages (from -r requirements.txt (line 3)) (1.2.15)
Requirement already satisfied: langchain-core in c:\python\lib\site-packages (from -r requirements.txt (line 4)) (1.2.27)
Requirement already satisfied: langchain-community in c:\python\lib\site-packages (from -r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: langchain-openai in c:\python\lib\site-packages (from -r requirements.txt (line 6)) (1.1.12)
Requirement already satisfied: langchain-text-splitters in c:\python\lib\site-packages (from -r requirements.txt (line 7)) (1.1.1)
Requirement already satisfied: langchain-classic in c:\python\lib\site-packages (from -r requirements.txt (line 8)) (1.0.3)
Collecting chromadb (from -r requirements.txt (line 9))
  Downloading chromadb-1.5.7-cp39-abi3-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: openai in c:\python\lib\site-packages (from -r requirements.txt (line 10)) (2.30.0)
Collecting pypdf (from -r requirements.txt (line 11))
  Downloading pypdf-6.10.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\python\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2025.3)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit->-r requirements.txt (line 2))
  Using cached altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit->-r requirements.txt (line 2))
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit->-r requirements.txt (line 2))
  Using cached cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (8.3.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit->-r requirements.txt (line 2))
  Using cached gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging>=20 in c:\users\sreemiraa.tn\appdata\roaming\python\python313\site-packages (from streamlit->-r requirements.txt (line 2)) (26.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (12.2.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit->-r requirements.txt (line 2))
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting protobuf<8,>=3.20 (from streamlit->-r requirements.txt (line 2))
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: pyarrow>=7.0 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (2.33.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (9.1.4)
Collecting toml<2,>=0.10.1 (from streamlit->-r requirements.txt (line 2))
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\sreemiraa.tn\appdata\roaming\python\python313\site-packages (from streamlit->-r requirements.txt (line 2)) (6.5.5)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\python\lib\site-packages (from streamlit->-r requirements.txt (line 2)) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit->-r requirements.txt (line 2))
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: jinja2 in c:\python\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2)) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2))
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2))
  Using cached narwhals-2.19.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: colorama in c:\users\sreemiraa.tn\appdata\roaming\python\python313\site-packages (from click<9,>=7.0->streamlit->-r requirements.txt (line 2)) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 2))
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 2))
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 2)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\python\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 2)) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\python\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 2)) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\python\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 2)) (2026.2.25)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in c:\python\lib\site-packages (from langchain->-r requirements.txt (line 3)) (1.1.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\python\lib\site-packages (from langchain->-r requirements.txt (line 3)) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\python\lib\site-packages (from langchain-core->-r requirements.txt (line 4)) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\python\lib\site-packages (from langchain-core->-r requirements.txt (line 4)) (0.7.26)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\python\lib\site-packages (from langchain-core->-r requirements.txt (line 4)) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\python\lib\site-packages (from langchain-core->-r requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in c:\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->-r requirements.txt (line 4)) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in c:\python\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in c:\python\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (1.0.9)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\python\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in c:\python\lib\site-packages (from langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\python\lib\site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in c:\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in c:\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->-r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->-r requirements.txt (line 4)) (0.25.0)
Requirement already satisfied: anyio in c:\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain->-r requirements.txt (line 3)) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 3)) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\python\lib\site-packages (from langchain-community->-r requirements.txt (line 5)) (2.0.49)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\python\lib\site-packages (from langchain-community->-r requirements.txt (line 5)) (3.13.5)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\python\lib\site-packages (from langchain-community->-r requirements.txt (line 5)) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\python\lib\site-packages (from langchain-community->-r requirements.txt (line 5)) (2.13.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\python\lib\site-packages (from langchain-community->-r requirements.txt (line 5)) (0.4.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\python\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\python\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\python\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->-r requirements.txt (line 5)) (1.2.2)
Requirement already satisfied: greenlet>=1 in c:\python\lib\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\python\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\python\lib\site-packages (from langchain-openai->-r requirements.txt (line 6)) (0.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\python\lib\site-packages (from openai->-r requirements.txt (line 10)) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\python\lib\site-packages (from openai->-r requirements.txt (line 10)) (0.13.0)
Requirement already satisfied: sniffio in c:\python\lib\site-packages (from openai->-r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\python\lib\site-packages (from openai->-r requirements.txt (line 10)) (4.67.3)
Requirement already satisfied: regex>=2022.1.18 in c:\python\lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai->-r requirements.txt (line 6)) (2026.3.32)
Collecting build>=1.0.3 (from chromadb->-r requirements.txt (line 9))
  Downloading build-1.4.3-py3-none-any.whl.metadata (5.8 kB)
Collecting pybase64>=1.4.1 (from chromadb->-r requirements.txt (line 9))
  Downloading pybase64-1.4.3-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb->-r requirements.txt (line 9))
  Downloading uvicorn-0.44.0-py3-none-any.whl.metadata (6.7 kB)
Collecting onnxruntime>=1.14.1 (from chromadb->-r requirements.txt (line 9))
  Downloading onnxruntime-1.24.4-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_api-1.41.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.41.0-py3-none-any.whl.metadata (2.6 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_sdk-1.41.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tokenizers>=0.13.2 in c:\python\lib\site-packages (from chromadb->-r requirements.txt (line 9)) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb->-r requirements.txt (line 9))
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
Collecting overrides>=7.3.1 (from chromadb->-r requirements.txt (line 9))
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting importlib-resources (from chromadb->-r requirements.txt (line 9))
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Collecting grpcio>=1.58.0 (from chromadb->-r requirements.txt (line 9))
  Downloading grpcio-1.80.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting bcrypt>=4.0.1 (from chromadb->-r requirements.txt (line 9))
  Downloading bcrypt-5.0.0-cp39-abi3-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in c:\python\lib\site-packages (from chromadb->-r requirements.txt (line 9)) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb->-r requirements.txt (line 9))
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting mmh3>=4.0.1 (from chromadb->-r requirements.txt (line 9))
  Downloading mmh3-5.2.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: rich>=10.11.0 in c:\python\lib\site-packages (from chromadb->-r requirements.txt (line 9)) (14.3.3)
Collecting pyproject_hooks (from build>=1.0.3->chromadb->-r requirements.txt (line 9))
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2)) (3.0.3)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2))
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2))
  Using cached rpds_py-0.30.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.9.0 in c:\python\lib\site-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 9)) (1.17.0)
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 9))
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting requests-oauthlib (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 9))
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 9))
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting flatbuffers (from onnxruntime>=1.14.1->chromadb->-r requirements.txt (line 9))
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: sympy in c:\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb->-r requirements.txt (line 9)) (1.14.0)
Collecting importlib-metadata<8.8.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting zipp>=3.20 (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting googleapis-common-protos~=1.57 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading googleapis_common_protos-1.74.0-py3-none-any.whl.metadata (9.2 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.41.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_exporter_otlp_proto_common-1.41.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.41.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_proto-1.41.0-py3-none-any.whl.metadata (2.4 kB)
Collecting protobuf<8,>=3.20 (from streamlit->-r requirements.txt (line 2))
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting opentelemetry-semantic-conventions==0.62b0 (from opentelemetry-sdk>=1.2.0->chromadb->-r requirements.txt (line 9))
  Downloading opentelemetry_semantic_conventions-0.62b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\python\lib\site-packages (from rich>=10.11.0->chromadb->-r requirements.txt (line 9)) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sreemiraa.tn\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->chromadb->-r requirements.txt (line 9)) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\python\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb->-r requirements.txt (line 9)) (0.1.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in c:\python\lib\site-packages (from tokenizers>=0.13.2->chromadb->-r requirements.txt (line 9)) (1.9.1)
Requirement already satisfied: filelock>=3.10.0 in c:\python\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb->-r requirements.txt (line 9)) (3.25.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import sys
!{sys.executable} -m pip install -q openai langchain langchain-community chromadb pypdf
!{sys.executable} -m pip install -q -U langchain-openai langchain-text-splitters langchain-classic streamlit

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

^C

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import os
os.environ["OPENAI_API_KEY"] = "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"
print("Environment ready")

Environment ready

# Step-1: Document Loading

In [11]:
import pandas as pd
from langchain_core.documents import Document

df = pd.read_csv("ecommerce_products_dataset.csv")
df.head()

,product_id,product_name,category,brand,price,rating,stock,discount_percent,seller,description
0,P10001,Mamaearth Moisturizer,Beauty,Mamaearth,1093.14,4.5,241,10,DailyDeals,Mamaearth Moisturizer is a budget-friendly bea...
1,P10002,Maybelline Makeup Brush Set,Beauty,Maybelline,3294.69,3.2,22,5,RetailHub,Maybelline Makeup Brush Set is a lightweight b...
2,P10003,Puma Men Cotton T-Shirt,Fashion,Puma,5423.15,3.3,162,30,QuickCart,Puma Men Cotton T-Shirt is a premium fashion p...
3,P10004,Penguin Productivity Habits,Books,Penguin,683.68,4.3,204,10,ValueMart,Penguin Productivity Habits is a stylish books...
4,P10005,McGraw Hill Travel Stories,Books,McGraw Hill,1307.56,3.2,163,5,DailyDeals,McGraw Hill Travel Stories is a high-performan...

In [12]:
documents = []
for _, row in df.iterrows():
    content = f'''
Product ID: {row["product_id"]}
Product Name: {row["product_name"]}
Category: {row["category"]}
Brand: {row["brand"]}
Price: {row["price"]}
Rating: {row["rating"]}
Stock: {row["stock"]}
Discount Percent: {row["discount_percent"]}
Seller: {row["seller"]}
Description: {row["description"]}
'''
    documents.append(
        Document(
            page_content=content,
            metadata={
                "product_id": row["product_id"],
                "product_name": row["product_name"],
                "category": row["category"],
                "brand": row["brand"]
            }
        )
    )

print("Total product documents:", len(documents))
print(documents[0])

Total product documents: 1000
page_content='
Product ID: P10001
Product Name: Mamaearth Moisturizer
Category: Beauty
Brand: Mamaearth
Price: 1093.14
Rating: 4.5
Stock: 241
Discount Percent: 10
Seller: DailyDeals
Description: Mamaearth Moisturizer is a budget-friendly beauty product with ergonomic design. Ideal for customers looking for reliable quality and value.
' metadata={'product_id': 'P10001', 'product_name': 'Mamaearth Moisturizer', 'category': 'Beauty', 'brand': 'Mamaearth'}

In [13]:
full_text = ""
for doc in documents:
    full_text += doc.page_content + "\n"

print("Documents:", len(documents))
print("Lines:", len(full_text.split("\n")))
print("Words:", len(full_text.split()))
print("Characters:", len(full_text))

Documents: 1000
Lines: 12001
Words: 44447
Characters: 316250

# Step-2: Split the data into Chunks

In [14]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=30)
chunks = text_splitter.split_documents(documents)
print("Total chunks:", len(chunks))

Total chunks: 1850

In [15]:
print(chunks[1])

page_content='Seller: DailyDeals
Description: Mamaearth Moisturizer is a budget-friendly beauty product with ergonomic design. Ideal for customers looking for reliable quality and value.' metadata={'product_id': 'P10001', 'product_name': 'Mamaearth Moisturizer', 'category': 'Beauty', 'brand': 'Mamaearth'}

# Step-3: Creating embeddings

In [19]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings()
embeddings

OpenAIEmbeddings(client=<openai.resources.embeddings.Embeddings object at 0x000002093FB50050>, async_client=<openai.resources.embeddings.AsyncEmbeddings object at 0x000002093FEC8590>, model='text-embedding-ada-002', dimensions=None, deployment='text-embedding-ada-002', openai_api_version=None, openai_api_base=None, openai_api_type=None, openai_proxy=None, embedding_ctx_length=8191, openai_api_key=SecretStr('**********'), openai_organization=None, allowed_special=None, disallowed_special=None, chunk_size=1000, max_retries=2, request_timeout=None, headers=None, tiktoken_enabled=True, tiktoken_model_name=None, show_progress_bar=False, model_kwargs={}, skip_empty=False, default_headers=None, default_query=None, retry_min_seconds=4, retry_max_seconds=20, http_client=None, http_async_client=None, check_embedding_ctx_length=True)

In [21]:
sample_embedding = embeddings.embed_query("Show premium electronics with high ratings")
print("Embedding length:", len(sample_embedding))

Embedding length: 1536

In [22]:
sample_docs = [
    "Wireless headphones with high ratings and premium build quality.",
    "Budget-friendly home products with good customer reviews."
]

embedded_vectors = embeddings.embed_documents(sample_docs)
print("Number of vectors:", len(embedded_vectors))
print("Vector dimension:", len(embedded_vectors[0]))

Number of vectors: 2
Vector dimension: 1536

# Step-4: Storing in Vector Stores

In [23]:
from langchain_community.vectorstores import Chroma

ecommerce_db = Chroma.from_documents(
    chunks,
    embeddings,
    persist_directory="ecommerce_rag_db"
)
ecommerce_db.persist()
print("Vector DB created successfully")

Vector DB created successfully

C:\Users\Sreemiraa.Tn\AppData\Local\Temp\ipykernel_18332\2855226093.py:8: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  ecommerce_db.persist()

# Step-5: Retrieval

In [24]:
retriever = ecommerce_db.as_retriever()
result = retriever.invoke("Show electronics products with premium quality and good ratings")
result

[Document(metadata={'product_name': 'Prestige LED Table Lamp', 'brand': 'Prestige', 'category': 'Home', 'product_id': 'P10184'}, page_content='Seller: PrimeSeller\nDescription: Prestige LED Table Lamp is a premium home product with ergonomic design. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Samsung Smart Watch', 'brand': 'Samsung', 'category': 'Electronics', 'product_id': 'P10349'}, page_content='Seller: QuickCart\nDescription: Samsung Smart Watch is a best-selling electronics product with ergonomic design. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Logitech Wireless Bluetooth Headphones', 'product_id': 'P10341', 'brand': 'Logitech', 'category': 'Electronics'}, page_content='Seller: TrustedStore\nDescription: Logitech Wireless Bluetooth Headphones is a premium electronics product with fast charging. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_id': 'P10233', 'product_name': 'Samsung Smart Watch', 'brand': 'Samsung', 'category': 'Electronics'}, page_content='Seller: ValueMart\nDescription: Samsung Smart Watch is a premium electronics product with easy maintenance. Ideal for customers looking for reliable quality and value.')]

In [25]:
for i in range(len(result)):
    print(result[i].metadata)

{'product_name': 'Prestige LED Table Lamp', 'brand': 'Prestige', 'category': 'Home', 'product_id': 'P10184'}
{'product_name': 'Samsung Smart Watch', 'brand': 'Samsung', 'category': 'Electronics', 'product_id': 'P10349'}
{'product_name': 'Logitech Wireless Bluetooth Headphones', 'product_id': 'P10341', 'brand': 'Logitech', 'category': 'Electronics'}
{'product_id': 'P10233', 'product_name': 'Samsung Smart Watch', 'brand': 'Samsung', 'category': 'Electronics'}

In [26]:
retriever = ecommerce_db.as_retriever()
result = retriever.invoke("Find beauty products with premium feel and strong ratings")
result

[Document(metadata={'product_name': 'Loreal Moisturizer', 'product_id': 'P10307', 'brand': 'Loreal', 'category': 'Beauty'}, page_content='Seller: TrustedStore\nDescription: Loreal Moisturizer is a premium beauty product with long battery life. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Lakme Makeup Brush Set', 'brand': 'Lakme', 'category': 'Beauty', 'product_id': 'P10736'}, page_content='Seller: TrustedStore\nDescription: Lakme Makeup Brush Set is a best-selling beauty product with AI-ready. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'brand': 'Nivea', 'product_id': 'P10573', 'product_name': 'Nivea Sunscreen', 'category': 'Beauty'}, page_content='Seller: TrustedStore\nDescription: Nivea Sunscreen is a best-selling beauty product with easy maintenance. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Minimalist Face Wash', 'product_id': 'P10923', 'category': 'Beauty', 'brand': 'Minimalist'}, page_content='Seller: PrimeSeller\nDescription: Minimalist Face Wash is a premium beauty product with machine washable. Ideal for customers looking for reliable quality and value.')]

# MultiQueryRetriever

In [27]:
from langchain_classic.retrievers import MultiQueryRetriever
from langchain_openai import OpenAI

llm = OpenAI(temperature=0)

In [28]:
llm_based_retriever = MultiQueryRetriever.from_llm(
    retriever=ecommerce_db.as_retriever(),
    llm=llm
)

In [29]:
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

In [30]:
question1 = "Suggest budget-friendly electronics with good ratings"
rel_docs1 = llm_based_retriever.invoke(question1)
rel_docs1

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:langchain_classic.retrievers.multi_query:Generated queries: ['1. Can you recommend affordable electronics with high ratings?', '2. What are some budget-friendly electronics that have received good ratings?', '3. Which electronics with good ratings are also budget-friendly?']
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[Document(metadata={'brand': 'Samsung', 'category': 'Electronics', 'product_name': 'Samsung Power Bank', 'product_id': 'P10128'}, page_content='Seller: TrustedStore\nDescription: Samsung Power Bank is a budget-friendly electronics product with AI-ready. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_id': 'P10124', 'category': 'Electronics', 'product_name': 'Samsung Power Bank', 'brand': 'Samsung'}, page_content='Seller: PrimeSeller\nDescription: Samsung Power Bank is a lightweight electronics product with noise cancellation. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Electronics', 'product_name': 'JBL Gaming Mouse', 'product_id': 'P10158', 'brand': 'JBL'}, page_content='Seller: TrustedStore\nDescription: JBL Gaming Mouse is a budget-friendly electronics product with long battery life. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Boat Wireless Bluetooth Headphones', 'product_id': 'P10748', 'category': 'Electronics', 'brand': 'Boat'}, page_content='Seller: TrustedStore\nDescription: Boat Wireless Bluetooth Headphones is a eco-friendly electronics product with AI-ready. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Electronics', 'brand': 'Logitech', 'product_id': 'P10660', 'product_name': 'Logitech Wireless Bluetooth Headphones'}, page_content='Seller: QuickCart\nDescription: Logitech Wireless Bluetooth Headphones is a budget-friendly electronics product with fast charging. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Electronics', 'brand': 'Logitech', 'product_name': 'Logitech Wireless Bluetooth Headphones', 'product_id': 'P10514'}, page_content='Seller: TrustedStore\nDescription: Logitech Wireless Bluetooth Headphones is a budget-friendly electronics product with AI-ready. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Anker Smartphone Case', 'product_id': 'P10623', 'category': 'Electronics', 'brand': 'Anker'}, page_content='Seller: TrustedStore\nDescription: Anker Smartphone Case is a budget-friendly electronics product with noise cancellation. Ideal for customers looking for reliable quality and value.')]

In [31]:
question2 = "Find travel-friendly products for frequent shoppers"
rel_docs2 = llm_based_retriever.invoke(question2)
rel_docs2

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:langchain_classic.retrievers.multi_query:Generated queries: ['1. What are some products that are suitable for frequent shoppers who travel often?', '2. Can you suggest any travel-friendly items for people who shop frequently?', '3. What are the best products for frequent shoppers who are always on the go?']
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[Document(metadata={'brand': 'Packt', 'category': 'Books', 'product_id': 'P10793', 'product_name': 'Packt Travel Stories'}, page_content='Seller: DailyDeals\nDescription: Packt Travel Stories is a durable books product with machine washable. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Adidas Handbag', 'brand': 'Adidas', 'product_id': 'P10464', 'category': 'Fashion'}, page_content='Seller: QuickCart\nDescription: Adidas Handbag is a customer-favorite fashion product with travel friendly. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Books', 'product_name': 'Pearson Travel Stories', 'brand': 'Pearson', 'product_id': 'P10898'}, page_content='Seller: QuickCart\nDescription: Pearson Travel Stories is a budget-friendly books product with machine washable. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Minimalist Perfume', 'product_id': 'P10071', 'category': 'Beauty', 'brand': 'Minimalist'}, page_content='Seller: ShopNest\nDescription: Minimalist Perfume is a best-selling beauty product with travel friendly. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Books', 'brand': 'HarperCollins', 'product_id': 'P10816', 'product_name': 'HarperCollins Travel Stories'}, page_content='Seller: QuickCart\nDescription: HarperCollins Travel Stories is a compact books product with noise cancellation. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'OReilly Productivity Habits', 'category': 'Books', 'product_id': 'P10762', 'brand': 'OReilly'}, page_content='Seller: QuickCart\nDescription: OReilly Productivity Habits is a durable books product with travel friendly. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'product_name': 'Minimalist Shampoo', 'category': 'Beauty', 'brand': 'Minimalist', 'product_id': 'P10787'}, page_content='Seller: QuickCart\nDescription: Minimalist Shampoo is a best-selling beauty product with fast charging. Ideal for customers looking for reliable quality and value.'),
 Document(metadata={'category': 'Books', 'product_id': 'P10242', 'product_name': 'Penguin Productivity Habits', 'brand': 'Penguin'}, page_content='Seller: QuickCart\nDescription: Penguin Productivity Habits is a best-selling books product with long battery life. Ideal for customers looking for reliable quality and value.')]

# Contextual Compression

In [32]:
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_classic.retrievers.document_compressors import LLMChainExtractor

llm = OpenAI(temperature=0)
compressor = LLMChainExtractor.from_llm(llm)

compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor,
    base_retriever=ecommerce_db.as_retriever()
)

In [33]:
compressed_docs = compression_retriever.invoke(question1)
compressed_docs[0].metadata

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"

{'product_name': 'JBL Gaming Mouse',
 'brand': 'JBL',
 'category': 'Electronics',
 'product_id': 'P10158'}

# RetrievalQA Chain

In [35]:
from langchain_classic.chains import RetrievalQA

llm = OpenAI(temperature=0)

Q_AChain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=llm_based_retriever
)

In [36]:
query = "Recommend a few highly rated fashion products for daily use and summarize why they fit."
docs = Q_AChain({"query": query})
docs["result"]

C:\Users\Sreemiraa.Tn\AppData\Local\Temp\ipykernel_18332\2683414395.py:2: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain-classic 0.1.0 and will be removed in 1.0. Use `invoke` instead.
  docs = Q_AChain({"query": query})
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"
INFO:langchain_classic.retrievers.multi_query:Generated queries: ['1. Can you suggest some top-rated fashion items that are suitable for everyday wear and explain why they are a good fit?', '2. What are some highly recommended fashion products that are perfect for daily use and can you provide a brief summary of their suitability?', "3. I'm looking for some fashion items that have received great ratings and are ideal for daily use. Can you give me a few recommendations and summarize why they are a good choice?"]
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 200 OK"

'\n1. Levis Casual Denim Jacket from PrimeSeller: This jacket is not only a best-selling product, but it also has a long battery life and is water resistant, making it perfect for daily use. It offers reliable quality and value for customers.\n\n2. Puma Yoga Leggings from UrbanBasket: These leggings are a customer-favorite and have a long battery life, making them ideal for daily use. They also offer reliable quality and value for customers.\n\n3. Zara Sunglasses from PrimeSeller: These sunglasses are a customer-favorite and have a long battery life, making them perfect for daily use. They offer reliable quality and value for customers.\n\n4. Nike Casual Denim Jacket from QuickCart: This jacket is a best-selling product with an ergonomic design, making it comfortable for daily wear. It also offers reliable quality and value for customers.\n\n5. Adidas Sunglasses from TrustedStore: These sunglasses are compact and machine washable, making them convenient for daily use. They also offer reliable quality and value for customers.\n\nOverall, these fashion products are highly rated and offer reliable quality and value for daily use. They also have features such as long battery life, water resistance, and machine washability, making them practical and convenient for customers.'

In [37]:
print(Q_AChain.combine_documents_chain.llm_chain.prompt.template)

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Helpful Answer:

Validation of the Results

In [38]:
test_data = pd.read_csv("Ecommerce_QA_Validation.csv")
test_data.head()

,Question,Expected_Answer
0,Show budget-friendly electronics with good rat...,Retrieve electronics items with relatively low...
1,Find products suitable for travel and daily use,Look for descriptions mentioning travel friend...
2,Which fashion products have strong customer ap...,Find fashion products with higher ratings and ...
3,Suggest home products with easy maintenance,Retrieve home category products whose descript...
4,Recommend beauty products with premium feel,Find beauty products with premium or customer-...

In [39]:
test_qa_pairs = []
for index, row in test_data.iterrows():
    question = row["Question"]
    answer = row["Expected_Answer"]
    test_qa_pairs.append({"question": question, "answer": answer})

print(test_qa_pairs)

[{'question': 'Show budget-friendly electronics with good ratings', 'answer': 'Retrieve electronics items with relatively lower price and rating above about 4.0.'}, {'question': 'Find products suitable for travel and daily use', 'answer': 'Look for descriptions mentioning travel friendly, compact, lightweight, or daily use.'}, {'question': 'Which fashion products have strong customer appeal?', 'answer': 'Find fashion products with higher ratings and attractive descriptions like stylish or customer-favorite.'}, {'question': 'Suggest home products with easy maintenance', 'answer': 'Retrieve home category products whose descriptions mention easy maintenance or practical usage.'}, {'question': 'Recommend beauty products with premium feel', 'answer': 'Find beauty products with premium or customer-favorite descriptions and good ratings.'}]

## Simple fallback retrieval without embeddings

In [40]:
def build_product_text(dataframe):
    text_cols = [
        "product_id", "product_name", "category", "brand", "price",
        "rating", "stock", "discount_percent", "seller", "description"
    ]
    for col in text_cols:
        dataframe[col] = dataframe[col].fillna("").astype(str)

    dataframe["product_text"] = (
        "Product ID: " + dataframe["product_id"] + ". " +
        "Product Name: " + dataframe["product_name"] + ". " +
        "Category: " + dataframe["category"] + ". " +
        "Brand: " + dataframe["brand"] + ". " +
        "Price: " + dataframe["price"] + ". " +
        "Rating: " + dataframe["rating"] + ". " +
        "Stock: " + dataframe["stock"] + ". " +
        "Discount Percent: " + dataframe["discount_percent"] + ". " +
        "Seller: " + dataframe["seller"] + ". " +
        "Description: " + dataframe["description"]
    )
    return dataframe

df = build_product_text(df)
df[["product_name", "product_text"]].head(2)

,product_name,product_text
0,Mamaearth Moisturizer,Product ID: P10001. Product Name: Mamaearth Mo...
1,Maybelline Makeup Brush Set,Product ID: P10002. Product Name: Maybelline M...

In [41]:
def simple_retrieve(dataframe, query, top_k=5):
    query_terms = [term.strip().lower() for term in query.replace("/", " ").replace(",", " ").split() if term.strip()]
    matches = []

    for _, row in dataframe.iterrows():
        text = str(row.get("product_text", "")).lower()
        score = sum(1 for term in query_terms if term in text)
        if score > 0:
            try:
                rating = float(row.get("rating", 0))
            except:
                rating = 0
            matches.append((score, row.get("product_name", ""), row.get("category", ""), rating, row.get("price", ""), row.get("description", "")))

    matches.sort(key=lambda x: (x[0], x[3]), reverse=True)
    return matches[:top_k]

In [42]:
query = "premium electronics high rating travel friendly"
results = simple_retrieve(df, query, top_k=5)

for item in results:
    print(item)

(5, 'Dell Portable SSD', 'Electronics', 4.7, '20260.79', 'Dell Portable SSD is a premium electronics product with travel friendly. Ideal for customers looking for reliable quality and value.')
(5, 'Logitech Bluetooth Speaker', 'Electronics', 4.5, '12111.09', 'Logitech Bluetooth Speaker is a high-performance electronics product with travel friendly. Ideal for customers looking for reliable quality and value.')
(5, 'Anker Bluetooth Speaker', 'Electronics', 3.7, '41379.13', 'Anker Bluetooth Speaker is a high-performance electronics product with travel friendly. Ideal for customers looking for reliable quality and value.')
(5, 'Sony USB-C Fast Charger', 'Electronics', 3.7, '21703.0', 'Sony USB-C Fast Charger is a premium electronics product with travel friendly. Ideal for customers looking for reliable quality and value.')
(5, 'JBL Power Bank', 'Electronics', 3.4, '23759.23', 'JBL Power Bank is a premium electronics product with travel friendly. Ideal for customers looking for reliable quality and value.')